### ISSUE TITLE
The `copy` command may copy duplicate data 

### ISSUE THREAD

**Issue by 9-2-1** [rustic-rs/rustic_core#146]
The `copy` command may copy duplicated blob.

How to reproduce:

1. Prepare a file that is large enough, for example, `ffmpeg.exe`
2. Copy `ffmpeg.exe` to `ffmpeg2.exe`, `ffmpeg3.exe`
3. Create a config file like this:
``` toml
[repository]
repository="source"
password="123456"

[[copy.targets]]
repository="target"
password="789012"
```
4. Save the config file as `config.toml`.
5. Create some snapshots:
``` bash
rustic -P config backup ffmpeg.exe
rustic -P config backup ffmpeg2.exe
rustic -P config backup ffmpeg3.exe
```
6. Copy source to target: `rustic -P config copy`
7. Compare sizes of two repositories and the target repository will be larger.
8. Prune the target repository and it will reported that there are unused data.

It seems that when copying data blobs in `src/command/copy.rs`, the index is not updated so duplicate data blobs are copied.

> *I realized this when copying a 300GB repo into a 512GB hard disk and encountered a surprising disk full.*
